// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATMDdkD9l_kekQu4rxPuGffQmpi_UbUU8',
    appId: '1:1056287524106:web:ae768952d6cc4525dee6f3',
    messagingSenderId: '1056287524106',
    projectId: 'eaze-51c53',
    authDomain: 'eaze-51c53.firebaseapp.com',
    storageBucket: 'eaze-51c53.firebasestorage.app',
    measurementId: 'G-2YMSP68J57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3qG6E9ikZw_AlV90cCMxJPppCuEJllv0',
    appId: '1:1056287524106:android:5ac0806e884300dedee6f3',
    messagingSenderId: '1056287524106',
    projectId: 'eaze-51c53',
    storageBucket: 'eaze-51c53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX6o26rx2kzTeuprFfapgJEeOUBypYhIs',
    appId: '1:1056287524106:ios:0535fc3f41ade8e0dee6f3',
    messagingSenderId: '1056287524106',
    projectId: 'eaze-51c53',
    storageBucket: 'eaze-51c53.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX6o26rx2kzTeuprFfapgJEeOUBypYhIs',
    appId: '1:1056287524106:ios:0535fc3f41ade8e0dee6f3',
    messagingSenderId: '1056287524106',
    projectId: 'eaze-51c53',
    storageBucket: 'eaze-51c53.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATMDdkD9l_kekQu4rxPuGffQmpi_UbUU8',
    appId: '1:1056287524106:web:bf78bd1c3090c467dee6f3',
    messagingSenderId: '1056287524106',
    projectId: 'eaze-51c53',
    authDomain: 'eaze-51c53.firebaseapp.com',
    storageBucket: 'eaze-51c53.firebasestorage.app',
    measurementId: 'G-SE1XBL5WKK',
  );

}